// Collection of embellishment patterns for names
export const embellishmentPatterns = [
  "(¯`·. _.· your name ·._ .·´¯)",
  "★ • ─☆。 o゚。 your name ★─☆｡ o゚。",
  "♡ *。 ・。 your name ＊。 ・。 ♡",
  "゚+.。.+゚ your name ゚+.。.+゚",
  "。 ,｡ +｡ ,｡ +｡ *｡ your name 。 *｡ +｡ ,｡ +｡ ,｡",
  "゚・。.。 ･ﾟﾟ･｡.｡ your name ･ﾟﾟ･｡.｡ ･ﾟﾟ･｡",
  ",.~*' *·~-. your name -(_",
  "・.・゚゚・.・゚・.・゚ your name ゚・.・゚・.・゚゚・.・",
  "。.*#:.' ゚.:*♪:.'.: your name .:♪*:.' ゚♭.:*.♪' ゚",
  "-- --^[ your name ]^-- --",
  "⋌⋚o*o⋛♥♡♥⋋✣⋌⋚o your name o⋛⋋✣⋌⋚o*♥♡♥*o⋛⋋",
  "•·.· ´¯`·.· your name •·.· ´¯`·.·",
  "'·. ¸¸.· ´´¯`··. _.· your name '·. ¸¸.· ´´¯`··. _.·",
  "★♡★♡★♡ your name ♡★♡★♡★",
  "( '·. _) your name ( '·. _)",
  "◆:*:◇:*:◆ your name ◆:*:◇:*:◆",
  "'*·~-. ,.-~*' your name '*·~-. ,.-~*'",
  "+。 ◇｡ + your name ゚+。 ◇｡ +",
  "Oº°' your name '°ºO",
  "· ´)› your name ‹('·",
  "・*:.。. .。.:*・゚ your name ゚・*:.。. .。.:*・",
  ".~·*' '· your name ·' '*·~.",
  "☺♡☻♡ your name ♡☻♡☺",
  ".~¹°ˆ your name ˆ°¹~.",
  ".。.:*・゚♡ your name ♡ ゚・*:.。",
  '×º°"\'"°º× your name •._.· ´)',
  "*゚゚゚・ ♫ *:..。 ♡ *゚ ゚゚・ your name ♫ *:..。 ♡*ﾟ¨ﾟﾟ･ ♫*:..｡",
  "—÷([' your name ´)]÷—",
  "—(•·÷[ your name ]÷·•)—",
  "—¤÷('[¤ your name ¤] ´)÷¤—",
  "·· ¤('×[¤ your name ¤]× ´)¤··",
  "· ´ '·» your name «· ´ '·",
  "]¦•¦[ your name ]¦•¦[",
  "'·., ,.· ´ your name '·., ,.·",
  "[\\'·.] your name [.· ´]\\",
  "('·.·• your name •·.·')",
  "• ´ ¥ '• your name • ´ ¥ '•",
  "•^v^–[ your name ]–^v^•",
  "·° '·• your name •· ´ °·",
  "§.· ´¨'°÷·.. your name ×,.· ´¨'°÷·..§",
  "]|I{•------» your name «------•}I|",
  "«· ´º ´·•[• your name •]•· ´º ´·»",
  "゚*:;;:*゚✿゚ฺ*:;;:*゚✿ฺ your name ✿゚ฺ*:;;:*゚✿゚ฺ*:;;:*゚",
  "ðº° , your name °ºð",
  ":; ☆;:*:; ☆;:*:; your name ☆;:*:; ☆;:*:; ☆;:",
  "°o.O.× your name ×.O.o°",
  "゚+.。.+゚ your name ゚+.。.+゚",
  "··· ^v ´ '×) your name (× ´ 'v^··",
  "⋆⁺₊⋆ ⋆⁺₊⋆ your name ⋆⁺₊⋆ ⋆⁺₊⋆",
  "꧁༺ your name ༻꧂",
  "•°¯`•• your name ••´¯°•",
  "▁ ▂ ▄ ▅ ▆ ▇ █ your name █ ▇ ▆ ▅ ▄ ▂ ▁",
  "✧･ﾟ: *✧･ﾟ:* your name *:･ﾟ✧*:･ﾟ✧",
  "╰┈➤ your name ➤┈╯",
  "★彡 your name 彡★",
  "◦•●◉✿ your name ✿◉●•◦",
  "『 your name 』",
  "≪ your name ≫",
  "【 your name 】",
  '˜"*°•.˜"*°• your name •°*"˜.•°*"˜',
  "٩(｡•́‿•̀｡)۶ your name ٩(｡•́‿•̀｡)۶",
  "¸,ø¤º°`°º¤ø,¸ your name ¸,ø¤º°`°º¤ø,¸",
  "▀▄▀▄▀▄ your name ▄▀▄▀▄▀",
  "(-_-) your name (-_-)",
  "•´¯`•. your name .•´¯`•",
  '×º°"˜`"°º× your name ×º°"˜`"°º×',
  "•._.••´¯``•.¸¸.•` your name `•.¸¸.•´´¯`••._.•",
  "¸„.~¹°ˆ˜¨ your name ¨˜ˆ°¹~.„¸",
  "ıllıllı your name ıllıllı",
  "▌│█║▌║▌║ your name ║▌║▌║█│▌",
  "×÷·.·´¯`·)» your name «(·´¯`·.·÷×",
  "•°o.O your name O.o°•",
  "¤¸¸.•´¯`•¸¸.•..>> your name <<..•.¸¸•´¯`•.¸¸¤",
  "—(••÷ your name ÷••)—",
  "¸,ø¤º°`°º¤ø,¸¸,ø¤º° your name °º¤ø,¸¸,ø¤º°`°º¤ø,¸",
  "➶➶➶➶➶ your name ➷➷➷➷➷",
  "↫↫↫↫↫ your name ↬↬↬↬↬",
  "·.¸¸.·♩♪♫ your name ♫♪♩·.¸¸.·",
  "【｡_｡】 your name 【｡_｡】",
  "`•.¸¸.•´´¯`••._.• your name •._.••`¯´´•.¸¸.•`",
  "∙∙·▫▫ᵒᴼᵒ▫ₒₒ▫ᵒᴼᵒ▫ₒₒ▫ᵒᴼᵒ your name ᵒᴼᵒ▫ₒₒ▫ᵒᴼᵒ▫ₒₒ▫ᵒᴼᵒ▫▫·∙∙",
  "¸„.~¹°ˆ˜¨ your name ¨˜ˆ°¹~.„¸",
  "░▒▓█ your name █▓▒░",
  "▀▄▀▄▀▄ your name ▄▀▄▀▄▀",
  "(-_-) your name (-_-)",
  "•´¯`•. your name .•´¯`•",
  '×º°"˜`"°º× your name ×º°"˜`"°º×',
  "•._.••´¯``•.¸¸.•` your name `•.¸¸.•´´¯`••._.•",
  "¸„.~¹°ˆ˜¨ your name ¨˜ˆ°¹~.„¸",
  "ıllıllı your name ıllıllı",
  "▌│█║▌║▌║ your name ║▌║▌║█│▌",
  "×÷·.·´¯`·)» your name «(·´¯`·.·÷×",
  "•°o.O your name O.o°•",
  "¤¸¸.•´¯`•¸¸.•..>> your name <<..•.¸¸•´¯`•.¸¸¤",
  "—(••÷ your name ÷••)—",
  "¸,ø¤º°`°º¤ø,¸¸,ø¤º° your name °º¤ø,¸¸,ø¤º°`°º¤ø,¸",
  "➶➶➶➶➶ your name ➷➷➷➷➷",
  "↫↫↫↫↫ your name ↬↬↬↬↬",
  "·.¸¸.·♩♪♫ your name ♫♪♩·.¸¸.·",
  "【｡_｡】 your name 【｡_｡】",
  "`•.¸¸.•´´¯`••._.• your name •._.••`¯´´•.¸¸.•`",
  "∙∙·▫▫ᵒᴼᵒ▫ₒₒ▫ᵒᴼᵒ▫ₒₒ▫ᵒᴼᵒ your name ᵒᴼᵒ▫ₒₒ▫ᵒᴼᵒ▫ₒₒ▫ᵒᴼᵒ▫▫·∙∙",
  "¸„.~¹°ˆ˜¨ your name ¨˜ˆ°¹~.„¸",
  "░▒▓█ your name █▓▒░",
]
